### ISSUE TITLE
Possibility of generating cache

### ISSUE THREAD

**Issue by avelino** [prest/prest#112]
In some applications (or endpoint, depends on the use) cache is required to not be accessing the database (PostgreSQL) in every request.

> by default it should be a key-value bank embedded inside prestd (no external dependencies) and support other external key-value banks with adapter architecture

Store key/value:
- key: endpoint + query string (GET)
- value: return body

configuration (TOML/ENV):
```
[cache]
time = 10M
store = bolt
sotrePath = "./"
```

`sotrePath`: native memory storage support (no path declaration required, `:memory:`)

Stores (adapters):
- [buntdb](https://github.com/tidwall/buntdb) - _we are not thinking about performance, but it should be faster than running a query in postgresql_, ~~([bolt](https://github.com/boltdb/bolt) `deprecated`)~~
- [badger](https://github.com/dgraph-io/badger)
- redis
- memcached

Times:
- `S` or `s`: second
- `M` or `m`: minute
- `H` or `h`: hour
- `D` or `d`: day

If there is no cache in the configuration register (access the Bank in real time).

**Comment by tiaguinho** [comment]
There is anybody working on this?

**Comment by fabriziomello** [comment]
I'm just worried with invalidation mechanism. Query heavy update datasets can lead us to wrong results using just a timeout.
