### ISSUE TITLE
Table name case sensitive issue

### ISSUE THREAD

**Issue by leopku** [prest/prest#200]
- pREST version (or commit ref): 0.2
- pREST endpoint: /
- PostgreSQL version: 9.6
- Operating system: macOS
- Go version: 1.8
- Log gist:

## Description
I had a table named with 'Reply'

run
```sh
curl http://localhost:3000/mydb/public/Reply 
```
it returns
```js
{
	"error": "pq: relation \"public.reply\" does not exist"
}
```

**Comment by crgimenes** [comment]
if we surround the table name with double quotation marks we solve this problem and also tables with  reserved words as name, like "user".

**Comment by felipeweb** [comment]
@leopku fixed will be available on next release

**Comment by leopku** [comment]
Many thanks @felipeweb .
