### ISSUE TITLE
Keep getting "error": "sql: statement is closed"

### ISSUE THREAD

**Issue by allochi** [prest/prest#205]
- pREST version (or commit ref): latest
- pREST endpoint:
curl -X GET http://127.0.0.1:6000/backend/public/publishers -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ'

- PostgreSQL version: postgres (PostgreSQL) 9.6.4
- Operating system: macOS 10.12.6
- Go version: go1.8.3 darwin/amd64
- Log gist:
{
	"error": "sql: statement is closed"

## Description

Hi,

I setup a TOML file, and run prest successfully, I call any endpoint and it's successful the first time, but then, after that I keep getting this error:

```
"error": "sql: statement is closed"
```

I'm not sure what is causing this.

**Comment by marioidival** [comment]
@allochi Thank you for reporting!

**Comment by crgimenes** [comment]
@felipeweb May be the new cache, take a look.

**Comment by felipeweb** [comment]
@allochi fixed!
