### ISSUE TITLE
Improve CORS support

### ISSUE THREAD

**Issue by tarnowsc** [prest/prest#208]
Hi,

While working with prest I've found that OPTIONS call is not supported, unfortunately this is extensively  used as preflight request. Also the Access-Control-Allow-Headers header with asterix was not working for my browser. Therefore I've created two PRs:
https://github.com/prest/middlewares/pull/6
https://github.com/prest/config/pull/6

Best Regards
Cezary

**Comment by felipeweb** [comment]
thank you @tarnowsc

**Comment by tarnowsc** [comment]
that was quick, many thanks
