### ISSUE TITLE
Access multiple database

### ISSUE THREAD

**Issue by jeffotoni** [prest/prest#212]
Hello everyone, I had the need to access several databases, and today using the prest I realize that I would have to upload a service to each bank if I wanted to use the prest.
It would be interesting to have in the file prest.toml the possibility of configuring several databases and the system understand this in my requests.

**Comment by felipeweb** [comment]
@jeffotoni  today if you want access multiples databases is  possible use `QUERIES` feature with `dblink` extension https://www.postgresql.org/docs/current/static/dblink.html

**Comment by felipeweb** [comment]
@jeffotoni i will start a brainstorm with the others maintainers, because to support this we will need to change the global state of the connection. I think it is good feature, but i'm ok with one pREST per database because pREST control database migrations too.

What do you think @marioidival @avelino @crgimenes @cassiobotaro and @gtsalles ?

**Comment by jeffotoni** [comment]
Thanks for the answer, yes I would have to change the global "DB" to a DBS MAP in memory.

**Comment by avelino** [comment]
What would be the use? `pREST as service` or `framework`?
If it's like service it's so easy to climb another service, one for each data base

**Comment by jeffotoni** [comment]
So that's what I said before, it's a reality that we live in everyday, and maybe it's isolated for you and it does not make sense for you to implement.
We are testing the pREST as a service only but it was only a note ...

Thank you.

**Comment by avelino** [comment]
The @fabriziomello implemented Multi database support https://github.com/prest/adapters/pull/25

**Comment by jeffotoni** [comment]
Caramba ....muito bom.... vou conferir....
