### ISSUE TITLE
Scanner.Scan must return error if result is empty

### ISSUE THREAD

**Issue by crgimenes** [prest/prest#214]
Using pREST as package the function Scanner.Scan must return an error if result is empty and Scan is receiving an object to be populated.

Example:
```
type item struct {
	Value string
}
sc := postgres.Query("SELECT * FROM itens items WHERE id=$1, itemID)
i:=item{} // <- only one item not an array
if err = sc.Err(); err != nil {
	return
}
err = sc.Scan(&i)
if err = sc.Err(); err != nil {
	if err==postgres.ErrEmptyResult { // my suggestion that it should return
		fmt.Println("empty result")
		return
	}
	fmt.Println(err) // something else went wrong.
	return
}
```

This is necessary because there is no way to know if the result is empty or if the record matches with the empty object.

A workaround is to pass an array instead of an empty object and then use len() to check if the result is empty.

```
iaux:=[]item{}
...
if len(i) == 0 {
	fmt.Println("empty result")
	return
}
i=iaux[0]
```

**Comment by felipeweb** [comment]
one other way that i like more than return an error is return the number of rows returned just following the io.Reader ideia that return the number of bytes readed
