### ISSUE TITLE
Providing initial data for models

### ISSUE THREAD

**Issue by avelino** [prest/prest#23]
It’s sometimes useful to pre-populate your database with hard-coded data when you’re first setting up an app. You can provide initial data with fixtures or migrations.

Supports:
- JSON
- YAML

Lib: https://github.com/go-testfixtures/testfixtures (*Test to see if it works well*)

**Comment by PedroVinicius** [comment]
I'll try to solve that.

**Comment by avelino** [comment]
more details in: https://github.com/prest/prest/issues/274
