### ISSUE TITLE
Enable jwt middleware customization

### ISSUE THREAD

**Issue by EltonSouza** [prest/prest#230]
When we want to create a custom jwt middleware, this is already possible, but the prest besides registering the customized middleware also registers the standard middleware, which often ends up taking out effect of the customized middleware

**Comment by franciscocpg** [comment]
I'm very interested in this issue.
IMO the simplest solution is to add a config to disable prest jwt middleware.
So [here](
https://github.com/prest/middlewares/blob/14bc08e7033d2c92c8657fa97ad0a9aca3515bff/config.go#L26-L28) instead of  using
```go
if !config.PrestConf.Debug { 
 	MiddlewareStack = append(MiddlewareStack, JwtMiddleware(config.PrestConf.JWTKey)) 
 } 
```
Use something like
```go
if !config.PrestConf.DisableJWTMiddleware { 
 	MiddlewareStack = append(MiddlewareStack, JwtMiddleware(config.PrestConf.JWTKey)) 
 } 
```
What do you guys think?
May I propose a PR for that?

**Comment by felipeweb** [comment]
i guess we can i little bit different 

```go
if !config.PrestConf.Debug  && config.PrestConf.EnableJWTDefault /*default true */ { 
 	MiddlewareStack = append(MiddlewareStack, JwtMiddleware(config.PrestConf.JWTKey)) 
 } 
```

**Comment by felipeweb** [comment]
@franciscocpg feel free to send a PR

**Comment by franciscocpg** [comment]
@felipeweb 
If we have a separate config for enable/disable the default jwt, do we still need to check debug config?
I mean `if config.PrestConf.EnableJWTDefault` wouldn't be enough?

**Comment by felipeweb** [comment]
Yes

**Comment by felipeweb** [comment]
@franciscocpg to maintain the default behavior we need both, the debug mode off enable jwt and  if we want customize jwt we need to disable default jwt so other env var
