### ISSUE TITLE
SSL Connection

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#234]
I was looking how prest works and saw that doesn't exist SSL connection configuration.
What do you guys think about implementing that?

**Comment by tiaguinho** [comment]
I'm implementing this feature.
I thought to put the configuration like this:

[ssl]
mode = "required"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

**Comment by avelino** [comment]
That's a good sign
```
[ssl]
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"
```

Does not need `mode = "required"`, if there is the SSL TOML node it is required

**Comment by tiaguinho** [comment]
But `mode` has 4 options:

* disable - No SSL
* require - Always SSL (skip verification)
* verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
* verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)

**Comment by avelino** [comment]
Added on documentation mode list pls
