### ISSUE TITLE
Support pREST run on Google App Engine

### ISSUE THREAD

**Issue by felipeweb** [prest/prest#241]
On GAE we can't use negroni server we need to use GAE server so the ideia is expose all handlers in a function to make possible register handlers on  GAE server

**Comment by avelino** [comment]
GAE today run PostgreSQL?

**Comment by crgimenes** [comment]
Yes, but it's in beta.
https://cloud.google.com/sql/docs/postgres/

**Comment by felipeweb** [comment]
after PRs are merged you can test GAE integration here https://github.com/felipeweb/blog-posts/tree/master/pREST-GAE just change env vars on app.yaml

**Comment by avelino** [comment]
Could write blogpost on pREST in Google App Engine, this would help the project
