### ISSUE TITLE
SSL connection always disable

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#250]
Commit 25 on repository adapters removes the ability to set SSL mode because is fixed to ```disable```.
So, if I try to connect using SSL mode in require mode the following error is returned.
```bash
{
	"error": "pq: no pg_hba.conf entry for host \"xxx.xxx.xxx.xxx\", user \"foo\", database \"bar\", SSL off"
}
```

**Comment by felipeweb** [comment]
Feel free to send a pull request
Em sáb, 2 de dez de 2017 às 10:02, Tiago Temporin <notifications@github.com>
escreveu:
