### ISSUE TITLE
Angular pREST doesn't work in Angular 5.1.0

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#252]
I have made some tests using angular-prest package in the newest version of Angular (5.1.0).
Some of the packages used in angular-prest are deprecated.

I want to know if you guys think it's interest that we update the package to be consistent with Angular changes.

**Comment by felipeweb** [comment]
feel free to send a PR, but always keep in mind ... maintain compatibility with the current API if possible

**Comment by tiaguinho** [comment]
Done!

PR: https://github.com/prest/angular-prest/pull/3
