### ISSUE TITLE
Packages with own versioning

### ISSUE THREAD

**Issue by avelino** [prest/prest#256]
pREST consists of several packages and is possible to use separately (isolated, he's got his own life.), we need to create release (version) for each.

In the documentation we should recommend using via `gopkg.in`, example:

```
import "gopkg.in/prest/adapters.v1"
```

**Comment by sebastianwebber** [comment]
@avelino that will be easier if `go get ` starts supporting a `git tag` like `npm` or another dependency manager tool. Do you know if it is possible?

**Comment by felipeweb** [comment]
we can use git tag now because dep and vgo support tag

**Comment by avelino** [comment]
this problem was solved in this issue #361
