### ISSUE TITLE
prest.toml is mandatory

### ISSUE THREAD

**Issue by felipeweb** [prest/prest#257]

**Comment by sebastianwebber** [comment]
@felipeweb can you provide some details about how I can reproduce the problem?

**Comment by felipeweb** [comment]
![image](https://user-images.githubusercontent.com/4874009/33958415-7d6b3268-e02b-11e7-935d-98e237b04cf2.png)

**Comment by felipeweb** [comment]
file must be optional

**Comment by avelino** [comment]
When it is declared environment variable via `docker-compose` **does not work**, we need to understand why
