### ISSUE TITLE
Add repository topic "automatic-api"

### ISSUE THREAD

**Issue by dbohdan** [prest/prest#260]
Could you add the topic `automatic-api` to your repository? Software that automatically exposes APIs to databases isn't well-cataloged. (There didn't even seem to be a list on GitHub, so I [started one](https://github.com/dbohdan/automatic-api).) It will be easier to discover if there is a standard [GitHub topic](https://help.github.com/articles/about-topics/), and `automatic-api` seems as good a candidate as any. Six projects [already use it](https://github.com/topics/automatic-api).

**Comment by sebastianwebber** [comment]
can you take a look into this @avelino ? =)

**Comment by avelino** [comment]
Done

**Comment by dbohdan** [comment]
Thank you! 👍
