### ISSUE TITLE
[proposal] new doc site and url addresses

### ISSUE THREAD

**Issue by sebastianwebber** [prest/prest#263]
Hi team!

Thinking about the pRest documentation website I came with a proposal: split the documentation in two branches: `master` and for a lack of a better name... `next`.

The main idea is put the main website with details only of the latest stable version (`master` branch) and create an new website with the next release documentation (`next` branch). By next release I refer to new features and bug fixes not yet released.

When we close the current development version we will merge the `next` branch into `master`

Any thoughts here? 

Some ideas how to implement this:

1. same web site:
    - main url: http://postgres.rest with a automatic redirect to http://postgres.rest/stable
    - next url: http://postgres.rest/next without redirect
1. another website:
    - main url: http://postgres.rest with a automatic redirect to http://stable.postgres.rest
    - next url: http://next.postgres.rest without redirect

Honestly, I don't like this naked domain approach but we can talk about in another time. perhaps with a few beers? =)

**Comment by avelino** [comment]
Minha proposta para URIs seria:

- https://postgres.rest/ = stable (branch master)
- https://postgres.rest/v2.0/ = version number (branch v2.0)

**Comment by sebastianwebber** [comment]
@avelino please write **in english**! :P

**Comment by crgimenes** [comment]
Hey @sebastianwebber, as we talk, it's okay if you start messing with the doc.  :)

**Comment by avelino** [comment]
It's been 5 years and we still haven't needed to think about documentation versioning, so I'm closing this issue.

When we get to that point, we'll open a new issue.
