### ISSUE TITLE
CORS is not working for ionic apps.

### ISSUE THREAD

**Issue by suvarapuprasad** [prest/prest#271]
1. Please speak English, this is the language everybody of us can speak and write.
2. Please ask questions or config/deploy problems on our pREST channel: https://gitter.im/nuveo/prest
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- pREST version (or commit ref):
- pREST endpoint:
- PostgreSQL version:
- Operating system:
- Go version:
- Log gist:

## Description

...

**Comment by felipeweb** [comment]
@suvarapuprasad could you provide more description about this? 
What is the error message posted by ionic?
