### ISSUE TITLE
pREST documentation theme

### ISSUE THREAD

**Issue by avelino** [prest/prest#272]
The theme we use today is not good for software documentation, it was made for package documentation (for this it suits you very well).

What do I say as software documentation?
We need a theme that supports sub-menu and with step-to-use (paging)

my recomendation: https://themes.gohugo.io/theme/hugo-theme-learn

Send feedback pls

**Comment by sebastianwebber** [comment]
looks awesome @avelino

**Comment by fabriziomello** [comment]
LGTM
