### ISSUE TITLE
Support other JWT signing algorithms (HS512...)

### ISSUE THREAD

**Issue by ccamel** [prest/prest#286]
- pREST version (or commit ref): 0.3.0 (3429dab0b8b5bf489c9c12337b88bbc1ba104eda)
- pREST endpoint: 
- PostgreSQL version: 10.3
- Operating system: Linux 4.15.8-1-ARCH
- Go version: 1.10
- Log gist: https://gist.github.com/ccamel/5aeea54dbfac5b398b5a70e0d38c0308

## Description

We are currently using `pREST` in my company and we use JWT authentication based on the HS512 algorithm for signing:

```json
{
  "alg": "HS512",
  "typ": "JWT"
}
```

But the middleware of `pREST` seems to only accept`HS256` algorithm (see [gist logs](https://gist.github.com/ccamel/5aeea54dbfac5b398b5a70e0d38c0308)), which is confirmed by the following code: https://github.com/prest/middlewares/blob/master/middlewares.go#L59

It would be really nice to have `pREST` supporting other signing algorithms.

**Comment by ccamel** [comment]
Would you be interrested by a PR ? I could have a look on this.

**Comment by marioidival** [comment]
@ccamel yes, good idea!

**Comment by felipeweb** [comment]
@ccamel good improvement, waiting for your PR 🎉

**Comment by avelino** [comment]
@ccamel update documentation’s pls
https://postgres.rest/configurations/

**Comment by ccamel** [comment]
@avelino Sure :+1:

**Comment by felipeweb** [comment]
Thanks @ccamel  🎉

**Comment by avelino** [comment]
Very very good man, thanks
