### ISSUE TITLE
query template cannot find its data

### ISSUE THREAD

**Issue by tgirod** [prest/prest#299]
I'm trying to insert a line into a table. Because there is base64 encoded data in the request and that I have to decode it server side, I wrote a SQL query to insert a line into the table. I tested the query directly with psql, it works. Then I moved the query to `queries/data/upload.write.sql` and changed it include my 3 fields:

```
INSERT INTO data(meta, texte, audio) VALUES
    ({{.meta}}, '{{.texte}}', decode({{.audio}}, 'base64'));
```

Then I ran this:

```
curl -XPOST "http://localhost:3000/_QUERIES/data/upload" \
    -d '{"meta":1, "texte":"pouet pouet", "audio":"W29iamVjdCBCbG9iXQ=="}'
```

And here is the result:

```
"error": "could not execute sql pq: syntax error at or near \"\u003c\", 
INSERT INTO data(meta, texte, audio) VALUES\n   
 (\u003cno value\u003e, '\u003cno value\u003e', decode(\u003cno value\u003e, 'base64'));"
```

Obviously the template engine didn't find the data to insert and replaced it with <no value>. What did I do wrong ?

**Comment by felipeweb** [comment]
@tgirod  scripts support params only in query string.

```
curl -XPOST "http://localhost:3000/_QUERIES/data/upload?meta=1&texte=pouet%20pouet&audio=W29iamVjdCBCbG9iXQ==
```

This should work.

**Comment by felipeweb** [comment]
@tgirod  i will close but feel free to reopen if don't work

**Comment by felipeweb** [comment]
Just for confirmation i make some tests to prove what i said yesterday and i am correct.

The Queries feature works only with query string as you can see here https://github.com/felipeweb/prest-issue-299

I am ok with it.

**Comment by tgirod** [comment]
OK. I guess it doesn't work with `multipart/form-data` either ?

**Comment by avelino** [comment]
`multi/form-data` not rest pattern (correct me if I'm wrong)

**Comment by tgirod** [comment]
@avelino From my limited knowledge of the subject, I don't see why `multipart/form-data` wouldn't be a REST pattern - it is stateless and it transmits data through a POST request.

Someone asked the same question [here](https://stackoverflow.com/questions/30364642/does-using-multipart-form-data-content-type-for-a-restful-post-api-a-good-practi)

From the answers, it looks like `multipart/form-data` is the canonical way to send binary data to a REST endpoint.

**Comment by felipeweb** [comment]
https://github.com/prest/template/pull/4
