### ISSUE TITLE
Running without config file

### ISSUE THREAD

**Issue by NasseNase** [prest/prest#303]
I followed the instructions on the Website and now i have a prest.toml file and the prest-windows-4.0-amd64 file in a folder.

This is how my toml file looks.:

PREST_DEBUG=true
migrations = "./migrations"
[http]
port = 8080
[jwt]
key = "secret"
algo = "HS256"
default = false
[pg]
host = "127.0.0.1"
user = "postgres"
pass = ""
port = 5432
database = "posts"
[ssl]
mode = "disable"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

When i start the .exe file it gives me the following output: 

2018/06/04 20:11:23 [warning] Running without config file.
2018/06/04 20:11:23 [warning] You are running pREST in public mode.
[negroni] listening on :3000

Could you explain me why it runs without a config file? Is the .toml not the config file? If it is, why is it ignored?

I am at a loss here...

**Comment by cassiobotaro** [comment]
Please remove line `PREST_DEBUG=true` and try again.

**Comment by felipeweb** [comment]
@NasseNase could you share what is request and response headers?

**Comment by felipeweb** [comment]
On master branch it works to me!
------------- my TOML ---------------------
[cors]
alloworigin = ["http://example.com"]

--------------------------------------------

**Comment by NasseNase** [comment]
This is what i get... 

![networkresponse](https://user-images.githubusercontent.com/7911925/41150372-209213ae-6b0e-11e8-89ac-14ddce88f441.png)

as you can see there is no Access-Control-Allow-Origin. I use the prest-windows-4.0-amd64 file from https://github.com/prest/prest/releases/tag/v0.3.0.

Strangely it seems i can see the right Response and no Error in the Network Tab BUT i get the error msg and no Response in my Javascript code...

**Comment by NasseNase** [comment]
Thanks a lot, that fixed my problem!
