### ISSUE TITLE
unexpected warning

### ISSUE THREAD

**Issue by cassiobotaro** [prest/prest#307]
- pREST version (or commit ref): master
- pREST endpoint: -
- PostgreSQL version: 10
- Operating system: linux
- Go version: 1.10.3
- Log gist: -

## Description

When start a simple project using prest as library, even I reconfigure restrict mode, warning about public mode is showed.

`[warning] You are running pREST in public mode.`

```go
package main

import (
	"github.com/prest/adapters/postgres"
	"github.com/prest/cmd"
	"github.com/prest/config"
)

func main() {
	config.Load()
	config.PrestConf.AccessConf.Restrict = true
	postgres.Load()
	cmd.Execute()
}
```

**Comment by avelino** [comment]
I think it's important to notify when you're in **unsafe mode**.
In your case this *forcing* to be insecure, thinking about who forgot a setting of the **development** environment in **production** environment it is important to be notified.
