### ISSUE TITLE
Documentation Problem - Custom middlewares > Disable JWT

### ISSUE THREAD

**Issue by romuloads** [prest/prest#308]
Good evening.
I'm following the disable-jwt documentation at: https://postgres.rest/prest-as-web-framework/custom-middlewares/disable-jwt/
For token generation it works perfectly.
However other framework urls like "http://127.0.0.1:8000/databases" do not always work by returning an empty array.
If I take the code from Custom middlewares the url returns to normal operation.
The framework version is the main version of git.

**Comment by felipeweb** [comment]
@romuloads  the docs is a bit outdated... you can use `PREST_JWT_DEFAULT=false` to disable

**Comment by avelino** [comment]
Documentation: https://postgres.rest/configurations/#authorization
