### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by cmnstmntmn** [prest/prest#317]
Does anyone managed to make it work with CockroachDB ?

from their docs, it seems that is PostgreSQL compatible at drivers level;

https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html

**Comment by fabriziomello** [comment]
Hi,

From the low level protocol seems we don't need to do anything to be compatible with CockroachDB, but I doubts we're compatible at SQL level perspective.

See more information on adapters repo (https://github.com/prest/adapters/blob/master/postgres/statements/queries.go).

Regards,

**Comment by cmnstmntmn** [comment]
hmm, it doesn't seems to work

**Comment by fabriziomello** [comment]
We'd love to see a PR from you... ;-)

**Comment by cmnstmntmn** [comment]
thank you @fabriziomello.

i'm going to close this issue
