### ISSUE TITLE
Message causes confusion

### ISSUE THREAD

**Issue by cassiobotaro** [prest/prest#320]
- pREST version (or commit ref): master
- pREST endpoint: -
- PostgreSQL version: 10
- Operating system: linux
- Go version: 1.10.3
- Log gist:
![image](https://user-images.githubusercontent.com/3127847/42649628-9447db5c-85e0-11e8-8f65-bb00a727ce4d.png)

## Description

Using this [prest.toml](https://github.com/cassiobotaro/demoprest/blob/master/prest.toml), but set PREST_PG_USER in environment with "blah", prest uses env as priority but shows that using prest.toml file, causing some confusion.

**Comment by avelino** [comment]
thanks @cassiobotaro
