### ISSUE TITLE
Convert Scanner to a list struct.

### ISSUE THREAD

**Issue by romuloads** [prest/prest#329]
- pREST version last
- PostgreSQL version: 9.6
- Operating system: Windows 10
- Go version: go1.10.1 windows/amd64

Good afternoon. I'm in trouble, it must be noob.
I am using the query function of the postgres.go file to do a query in the database but I can only convert it to struct when it returns a line. How can I convert the Scanner that returns to a list struct.
Ex:
type Pessoa struct {
	Id       int `json:"id"`
	Nome     string `json:"nome"`
	Email    string `json:"email"`
	//DataNascimento string `json:"data_nascimento"`
	Senha    string `json:"senha"`
	Ativo    bool `json:"ativo"`
	Tipo 	 string `json:"tipo"`
	Telefone string `json:"telefone"`
	Celular	 string `json:"celular"`
}

type Pessoas struct  {
	Pessoas []Pessoa `json:"pessoa"`
}

How to Convert Scanner to a Peoples list struct.

**Comment by felipeweb** [comment]
@romuloads  suppose you have output from DB like bellow

```
{"pessoa":[{}, {}]}
```
you can do

```
var p Pessoas
sc.Scan(&p)
```

**Comment by romuloads** [comment]
When the db returns a line this mode works fine "sc.Scan (& p)" however when it is a list. It returns the following error message: "rows returned is not 1". In this case it returns 49 rows.
       quant, err := sc.Scan(&pessoas)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
	}
	if quant >= 1{
		fmt.Println(pessoas)
	}

**Comment by cassiobotaro** [comment]
@romuloads instead of create a struct Pessoas, just use []Pessoas.
```go
pessoas := make([]Pessoa, 0)
quant, err := sc.Scan(&pessoas)
if err != nil {
http.Error(w, err.Error(), http.StatusBadRequest)
}
if quant >= 1{
fmt.Println(pessoas)
}
```

**Comment by romuloads** [comment]
Thank you Cassiobotaro. I help a lot. Worked perfectly.
