### ISSUE TITLE
Returning sql clause on (at least) PATH/PUT query?

### ISSUE THREAD

**Issue by xulien** [prest/prest#331]
hi and thanks for this project.

Is there any reason to not implement the "returning" sql clause that i would haven't thougth of?

I use redux with pRest and it's hard to do an Select after an Update and deal with asynchonous  action call,
it could be a nice improvement on PATH/PUT to have something like "?_returning=id&returning=field"

in case, i can deep into, and try to provide a PR?

**Comment by felipeweb** [comment]
@xulien feel free to send a pull request it is very helpful, but please always return entire object, just to follow a pattern, because insert operation always return entire object

**Comment by xulien** [comment]
@felipeweb thx, I'll work on it.
Concerning entire object, what about heavy object with base64 image field and a boolean field when you just change the boolean value ?! it may be a little excessive but what a waste of resources.

What do you think about a query without "_returning" flag => actual response, "_returning=" or "_returning=*" => entire object, "_returning=field" => only the field desire. it should be optional.

Insert and Update hasn't the same intent and Insert itself hasn't the same response than others verbs, why it should be a pattern?

and last thougth, it seems to me that Mysql hasn't the "returning" clause, so it will be a postgresql only feature

**Comment by felipeweb** [comment]
https://github.com/prest/controllers/pull/20
