### ISSUE TITLE
could not execute template SQL

### ISSUE THREAD

**Issue by learningandworking** [prest/prest#341]
## Description

While using Prest to working with an existing SQL script(under foo folder), it informs issues as below. I tried to double-check in document and somewhere else to clarify, but not sure what's wrong. Hope you can take a look at it and give ideas to solve

**URL to run** 
```http://127.0.0.1:6000/_QUERIES/foo/some_get?field1=bar```

**Config file:** 
```location = "./queries/"```

**SQL file:**
```SELECT * FROM table WHERE name = "{{.field1}}";```

**Error(using Postman tool to test):**
```
{
    "error": "could not parse script foo/some_get, could not execute template template: queries\\foo\\some_get.read.sql: \"queries\\\\foo\\\\some_get.read.sql\" is an incomplete or empty template"
}
```
**Windows7 Structure folder:**
```D:
--prest
--------queries
----------------foo

```

- pREST version (or commit ref): 0.3.4
- PostgreSQL version: 11.1
- Operating system: Windows 7 , Windows 8.1
- API testing tool: Postman

**Comment by felipeweb** [comment]
Remove ; in the end and it works

**Comment by felipeweb** [comment]
Feel free to reopen if it don’t work

**Comment by vmaravind96** [comment]
@learningandworking did this solution work for you?

**Comment by vmaravind96** [comment]
I tried removing the ; but I get the same error.

**Comment by herodem** [comment]
I have the same problem. Some solution?

**Comment by palevi67** [comment]
Same problem here under W10, with or without trailing semicolon ... :-(

**Comment by palevi67** [comment]
@felipeweb please consider reopening this issue!

**Comment by felipeweb** [comment]
Do you want to send a PR? @palevi67 or @vmaravind96
