### ISSUE TITLE
Need example of $in filter. $in.value works but $in.[value1,value2] does not

### ISSUE THREAD

**Issue by RaviShankarPandey** [prest/prest#342]
I am trying to use $in filter on a table column. My URI looks like this:
http://0.0.0.0:3000/DB/SCHEMA/TABLE?column=$in.[value1,value2]
Where DB, SCHEMA,TABLE,column,value1 and value2 are some values. It returns an empty array []. However when I run the query in my Postgres client for value1 and value2 filter it returns rows of data. 
Can someone please give me an example on $in filter?

- pREST version (or commit ref):
- pREST endpoint:
- PostgreSQL version:9.6.6
- Operating system:MAC OS
- Go version:
- Log gist:

## Description

...

**Comment by AbhinavGuleria** [comment]
Hey Ravi,

It worked for me if i gave filter as 
column=$in.value1,value2,value3 so on

Thank you,
Abhinav

**Comment by RaviShankarPandey** [comment]
Thank you, Abhinav . it helped .
