### ISSUE TITLE
Bad docker image

### ISSUE THREAD

**Issue by ccamel** [prest/prest#345]
- pREST version (or commit ref): v0.3.4
- pREST endpoint: -
- PostgreSQL version: PostgreSQL 11.1
- Operating system: x86_64-pc-linux-gnu
- Go version: 1.11.5
- Log gist: -

## Description

The container `prest/prest:v0.3.4` fails to start:
```sh
> docker run -e PREST_HTTP_PORT=3000 -e PREST_PG_HOST=127.0.0.1 -e PREST_PG_USER=postgres -e PREST_PG_PASS=pass prest/prest:v0.3.4

standard_init_linux.go:207: exec user process caused "no such file or directory"
```

Same behaviour for tags `v0.3.3`, `v0.3.2` and `v0.3.1`. Only the tag `latest` (which is older than the previous ones) works.

**Comment by tsmethurst** [comment]
You need to install glibc in the Docker container

**Comment by ccamel** [comment]
@tsmethurst Oh, yes, that's right. thanks!

To fix that, I've just *symlinked* libraries `musl` to `glibc` (as they are [compatible](https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker/35613430#35613430)), and it worked!

```
FROM alpine:3.7

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

COPY prest /prest

CMD ["/prest"]
```

**Comment by airjulio** [comment]
Is there any plan to make the Docker image with tag `latest` to be the latest version on the repo?

**Comment by airjulio** [comment]
> You need to install glibc in the Docker container

@tsmethurst Could you tell me how to do that using the current Dockerfile, please? Thank you for your help!

**Comment by tsmethurst** [comment]
@airjulio 

How I do it in my Dockerfiles:
```
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk && \
    apk add glibc-2.29-r0.apk && rm glibc-2.29-r0.apk /etc/apk/keys/sgerrand.rsa.pub
```

**Comment by avelino** [comment]
Fixed
