### ISSUE TITLE
Prest docker connects to 127.0.0.1 instead of envrionment var

### ISSUE THREAD

**Issue by darox** [prest/prest#351]
- pREST version (or commit ref): Latest docker image
- pREST endpoint: - 
- PostgreSQL version: latest postgres docker image
- Operating system: Ubuntu 18.04
- Go version: - 
- Log gist: - 

I have deployed prest in docker with the following command:
`sudo docker run -d \
-e PREST_HTTP_PORT=8092 \
-e PREST_PG_HOST=172.19.0.106 \
-e PREST_PG_USER=postgres \
-e PREST_PG_PASS=pass \
--name prod-prest \
--restart=always \
--net prod-network --ip 172.19.0.107 \
prest/prest `

But `sudo docker logs prod-prest` returns:
2019/04/18 14:59:33 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:00:34 [msg] Using ./prest.toml config file.
2019/04/18 15:00:34 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:01:36 [msg] Using ./prest.toml config file.
2019/04/18 15:01:36 [error] dial tcp 127.0.0.1:5432: connect: connection refused
2019/04/18 15:02:37 [msg] Using ./prest.toml config file.
2019/04/18 15:02:37 [error] dial tcp 127.0.0.1:5432: connect: connection refused

Why does prest try to connect to 127.0.0.1 instead of the specified envrionment variable?

Thanks!

**Comment by tdenizen** [comment]
I'm getting the same issue
