### ISSUE TITLE
PREST docker dial tcp 127.0.0.1:54320: connection refused

### ISSUE THREAD

**Issue by wshixjr** [prest/prest#352]
I am following the document to install the prest, after running the command:
docker run -e PREST_HTTP_PORT=3000 -e PREST_PG_HOST=127.0.0.1 -e PREST_PG_PORT=5432 -e PREST_PG_USER=postgres -e PREST_PG_PASS=123456 prest/prest
there is the error
9/04/20 14:14:18 [error] dial tcp 127.0.0.1:54320: connect: connection refused

but i am using go get to install prest and run prest local can access the prest
How to resolve the problem?

**Comment by Leocete** [comment]
any solutions to this problem?

**Comment by avelino** [comment]
> any solutions to this problem?

```
prest_1     | Waiting for port postgres:5432 to become available...
prest_1     | Ready hosting postgres to port 5432 !
prest_1     | 2021/02/22 15:06:51 [warning] adapter is not set. Using the default (postgres)
prest_1     | 2021/02/22 15:06:51 [warning] You are running pREST in public mode.
prest_1     | [prest] listening on 0.0.0.0:3000 and serving on /
```

yep, this issue got lost from my vision, sorry for not closing it earlier
