### ISSUE TITLE
mistakes in the package architecture (fail), proposed to simplify evolution and project maintenance

### ISSUE THREAD

**Issue by avelino** [prest/prest#361]
**Want to start talking sorry** 😭

In 2017 I opened this issue proposing architectural change: https://github.com/prest/prest/issues/190

In my view we miss the architecture split into many packages, generating many PR in any repositories. I would like to start planning a new architecture of internal pREST packages (one repository).

```
github.com/prest/prest
├── README.md
├── adapters
│   ├── adapter.go
│   ├── go.mod
│   ├── mock
│   │   ├── mock.go
│   │   └── mock_test.go
│   ├── ...
├── cmd
│   ├── create.go
│   ├── down.go
│   ├── prestd
│   │   ├── go.mod
│   │   ├── go.sum
│   │   ├── main.go (initial point)
│   │   └── prest.toml
│   ├── ...
├── config
│   ├── ...
├── middlewares
│   ├── ...
├── controllers
│   ├── ...
├── ...
```

In this way it is possible to use as a framework (extend the pREST by importing internal packages without vendor directory conflict).

**Comment by joelmdesouza** [comment]
Uses vendor inside cmd folder, is it works well?

**Comment by avelino** [comment]
> Uses vendor inside cmd folder, is it works well?

yep, check initial **WIP PR** here: https://github.com/prest/prest/pull/370
