### ISSUE TITLE
JWT role claim

### ISSUE THREAD

**Issue by tbmale** [prest/prest#363]
Hello,

  I couldn't find any reference in the docs nor the issues about using the JWT claims.
Can I use the role claim from an JWT token as the pg role for the session ? (à la postgrest)

Thanks

**Comment by pyramation** [comment]
this library looks awesome! I really want to use prest, however, I'm in the same boat as @tbmale .... just looking for some docs on how to use this.

Are there any examples out there for integrating a JWT system? 

Here is how I've done it and would like to:

### issuing and storing tokens/sessions

The way I typically do it, is I've actually implemented a table with my own tokens, and a function for validating and issuing tokens to users. The table is private, and never exposed to public. The function will check against a users email/password to issue a token. 

### authenticating requests

Then when client sends requests, token is pulled off to be authenticated, before every request, and then sets some settings using `set_config`, which changes `role` and gives some meta-data that my policies use for RLS:

```sql
select set_config('role', 'app_user', true);
select set_config('jwt.claims.role_id', '681f005b-f897-467f-86de-8f4e59bfb12f', true);
```

### write SQL using this information in procedures and policies

Now in using RLS and policies, you can use this information:

```sql
CREATE POLICY can_do_something ON some_table
  FOR UPDATE
  USING (
    current_setting('jwt.claims.role_id')::uuid = sender_id
  );
```

**Comment by pyramation** [comment]
@avelino @joelmdesouza

**Comment by avelino** [comment]
We are working on the implementation of standard authentication, can be followed here https://github.com/prest/prest/issues/276

**Comment by avelino** [comment]
cc @tiaguinho

**Comment by avelino** [comment]
implementation of authentication endpoint completed, we will be grateful for your feedback
view more: https://docs.postgres.rest/query-statements/#auth-auth---post
