### ISSUE TITLE
Send JSON directly from Postman creates an error

### ISSUE THREAD

**Issue by syahnetwork** [prest/prest#366]
<a href="https://ibb.co/fqKkHJL"><img src="https://i.ibb.co/Bc7yBkF/Screenshot-from-2020-05-12-16-15-00.png" alt="Screenshot-from-2020-05-12-16-15-00" border="0"></a>

above is the output error. I search on stackoverflow , then found to use JSON.parse to already stringify data as one of the solution

**Comment by tiaguinho** [comment]
Hi @syahnetwork, can you share the request headers?

Thank you!

**Comment by avelino** [comment]
You are using `x-www-from-urlencoded`, we support `JSON Data`, since this doubt came up I think it is important to put in the documentation how to use pREST on the postman client

**Comment by syahnetwork** [comment]
> You are using `x-www-from-urlencoded`, we support `JSON Data`, since this doubt came up I think it is important to put in the documentation how to use pREST on the postman client

thank you for the explanation, I'll try again adding data :)

**Comment by syahnetwork** [comment]
> Hi @syahnetwork, can you share the request headers?
> 
> Thank you!

application/x-www-form-urlencoded which is not supported I guess , thank you :+1:

**Comment by syahnetwork** [comment]
The issue has been resolved, thank you :100: :+1:
