### ISSUE TITLE
create docker compose file

### ISSUE THREAD

**Issue by avelino** [prest/prest#399]
Write docker file compose with all dependencies to upload pREST server - simplify and document use for new collaborators

- based on the code (development, can be via `go run` and _source mount volume_)
- based on the docker image (production)

related #388

**Comment by fabriziomello** [comment]
@avelino we have a [docker-compose.yml](https://github.com/prest/prest/blob/master/docker-compose.yml) already so what's the point here?

IMHO for a better user experience we should create a separate repository with a complete demo... something like a tutorial.

**Comment by avelino** [comment]
@fabriziomello compose was not working (so I opened this issue), correction in the PR mentioned above
