### ISSUE TITLE
Travis error on docker command

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#408]
Travis can't run tests because of an error on the docker command.

***Error:***
```bash
The command "docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"" failed and exited with 1 during .
```

***Last test***
https://travis-ci.org/github/prest/prest/jobs/722834969

**Comment by avelino** [comment]
It was some oscillation in the TravisCI or Docker Hub, problem solved
