### ISSUE TITLE
Make request headers accessible from SQL scripts templates

### ISSUE THREAD

**Issue by ccamel** [prest/prest#409]
**Is your feature request related to a problem? Please describe.**

I have successfully deployed `prest` to production for some time to run SQL scripts from query parameters. However, for some reason, I now need to access query headers to configure the SQL script, which is unfortunatly not currently possible.

**Describe the solution you'd like**

I'd like to have the query headers available in the data object when executing SQL script templates. 

**Additional context**

Implementation of the feature is pretty straightforward and I can do a PR if desired.

**Comment by avelino** [comment]
@ccamel It will be important to count on your support doing this implementation, I am waiting for your PR
