### ISSUE TITLE
release tag question

### ISSUE THREAD

**Issue by chenrui333** [prest/prest#412]
👋  It looks like the release tagging process is not quite stable (as you can see in [here](https://github.com/Homebrew/homebrew-core/pull/59724) and [here](https://github.com/Homebrew/homebrew-core/pull/60701)), I wonder if that is intentional, thanks!

**Comment by avelino** [comment]
We have a problem, I'm working to solve it, sorry. I'll send an update of the formula solving this problem.

**Comment by chenrui333** [comment]
@avelino thanks for confirming the issue, I do have an open PR addressing it. All good!

**Comment by avelino** [comment]
@chenrui333 I looked at this issue and I couldn't understand what I need to do to solve, can you help me?

our release generation process is working via `git tag + goreleaser`

**Comment by chenrui333** [comment]
Over the past year, it looks much better. Thus, closing this issue.

@avelino what I was looking for is to make sure there is no re-tagged release (then the release artifact would not be changed), let me know if that makes sense.
