### ISSUE TITLE
Improve local tests execution

### ISSUE THREAD

**Issue by fabriziomello** [prest/prest#510]
Nowadays to execute pREST tests we need to create and configure a PostgreSQL instance separately before the execution and sometimes it can be a completely pain if you don't have too much experience with setting up the database.

The idea here is to discuss and improve the current way of running tests locally, maybe creating a Makefile. Any ideas are very welcome!

**Comment by felipeweb** [comment]
We can use https://github.com/zombiezen/postgrestest to avoid any pre configuration
