### ISSUE TITLE
Documentation theme

### ISSUE THREAD

**Issue by avelino** [prest/prest#542]
We need to improve the appearance of the prest documentation, I found this theme interesting
- https://themes.gohugo.io/hugo-geekdoc/
- https://github.com/onweru/compose

**Comment by wuzhen1228** [comment]
I think better documentation should be done first!  lol

**Comment by avelino** [comment]
> I think better documentation should be done first! lol

@wuzhen1228 I agree, we are waiting for your contribution, the project only gets better when we have other people contributing
