### ISSUE TITLE
Implement build with bazel

### ISSUE THREAD

**Issue by tiaguinho** [prest/prest#545]
Add bazel as the build tool for prest

**Comment by avelino** [comment]
@tiaguinho I like new things, describe what is the difference between goreleaser (used today) and bazel, what bazel does best and especially worst

I saw that you have to create one bazel file per package, is that bad

Update the description with this information

**Comment by avelino** [comment]
@tiaguinho can you defend why change the goreleaser for bazel? this way we can involve our technical team to discuss the best solution for prest.

are you still interested in continuing to contribute to this (#546) implementation?
