### ISSUE TITLE
`ltree` field support

### ISSUE THREAD

**Issue by avelino** [prest/prest#554]
I like the idea of supporting `ltree` field

To support this type of fields would be to implement the list of operators (`Table F.13. ltree Operators`), here https://github.com/prest/prest/blob/9b677c30fef3f06f62f8a22cafd55a075655bdbc/adapters/postgres/postgres.go#L1028:L1067

_Originally posted by @kalmarz in https://github.com/prest/prest/discussions/504_

**Comment by diasbruno** [comment]
If nobody is working on this, I can give it a try. 
Let me know if this is still open, @avelino and @arxdsilva.

**Comment by avelino** [comment]
@diasbruno the issue has not been implemented, I look forward to your contribution
If you need any help, I'm here

**Comment by arxdsilva** [comment]
@diasbruno feel free to contribute, we'll be here to help! (:

**Comment by diasbruno** [comment]
Thanks. Let's see how this goes...
