### ISSUE TITLE
PREST_SSL_MODE is PostgreSQL config not http ssl - and other ssl variables

### ISSUE THREAD

**Issue by avelino** [prest/prest#561]
We are using the `PREST_SSL_MODE` variable for ssl configuration of the postgres not http server.

The variable name refers to prest's ssl configuration (api rest, i.e. http) not postgres

We need to change it to: `PREST_PG_SSL_MODE`

We can't break compatibility with whoever is using this variable, we need to give a ⚠️  **warning** to whoever is using

**Vars:**
- `PREST_SSL_MODE ` -> `PREST_PG_SSL_MODE`
- `PREST_SSL_CERT ` -> `PREST_PG_SSL_CERT`
- `PREST_SSL_KEY ` -> `PREST_PG_SSL_KEY`
- `PREST_SSL_ROOTCERT ` -> `PREST_PG_SSL_ROOTCERT`

**Comment by fabriziomello** [comment]
+1

I'm just wondering if we should maintain it in sync with [libpq environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) just adding `PREST_` prefix.

**Comment by letushka** [comment]
Guys, I just added this thread https://github.com/prest/prest/discussions/712 asking about possibility of running prest HTTPS? I wonder if prest with https is possible? 
How can one use JSON calls to prest from HTTPS sites?

**Comment by avelino** [comment]
@arxdsilva has this issue been fixed?

**Comment by arxdsilva** [comment]
@avelino yes it has been fixed recently
