### ISSUE TITLE
_distinct=true doesn't work

### ISSUE THREAD

**Issue by OlegZharkov** [prest/prest#569]
please help, I was following official docs https://docs.prestd.com/query-statements/ and I couldn't make distinct work. 
first of all it says ```"?distinct=true"```, so I tried 
?_select=sample&_page_size=10&_page=1&distinct=true
and it says: 
```
{
	"error": "pq: column \"distinct\" does not exist"
}
```
if I run it with:
?_select=sample&_page_size=10&_page=1&_distinct=true
the result is:
```
[{"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}, 
 {"sample":"ERR5549561"}]
 ```

which doesn't look really distinct, what is the appropriate way to fix it? thanks for reading this issue!

**Comment by avelino** [comment]
@OlegZharkov **distinct** must start with prefix `_` (example: `_distinct=true`), in your query you are using without `_`

how I want it:
```
?_select=sample&_page_size=10&_page=1&distinct=true
```

as it should be:
```
?_select=sample&_page_size=10&_page=1&_distinct=true
```

**Comment by OlegZharkov** [comment]
Thanks a lot for answering @avelino! could you please fix it in the docs? https://docs.prestd.com/query-statements/#filters-parameters-query-string---get

Anyway, I tried it with `_distinct=true` and it still doesn't work. Here's an example:
http://coviddbtest.gq/app_db/api/isolates?_select=sample&_page_size=10&_page=1&_distinct=true

**Comment by avelino** [comment]
updated documentation, I will understand the possible problem, keep the issue updated

**Comment by OlegZharkov** [comment]
> updated documentation, I will understand the possible problem, keep the issue updated

thanks for working on it! @avelino

**Comment by avelino** [comment]
@OlegZharkov problem fixed by @louis77 (my eternal gratitude), generated a new version

## docker
- `prest/prest:latest`
- `prest/prest:v1.0.9`
- `prest/prest:v1`

https://github.com/prest/prest/releases/tag/v1.0.9
