### ISSUE TITLE
querying a non existent db breaks new requests

### ISSUE THREAD

**Issue by arxdsilva** [prest/prest#578]
**Describe the bug**
Running the server with default configs and querying a db that isnt configured makes the server misbehaviour and use as the default DB one that doesnt exist. This makes all subsequent requests (that dont use the db in path) to fail, also is valid when having a high amount of requests in multiple DBs, as they may fail due to how the server is being setted right now.

**To Reproduce**
https://www.youtube.com/watch?v=Lis9Nwg_coo

**Expected behavior**
Querying a db that is not configured should return a 4xx error, also ideally the db should be setted per request instead of "globally" as it is right now.

**Desktop (please complete the following information):**
 - pREST version (or commit ref): 1.0.8
 - pREST endpoint: `/{db}/{schema}/{table}` + `any other`
 - PostgreSQL version: 13
 - OS: [e.g. Debian Tid]: mac
 - Go version: 1.16.5

**Comment by avelino** [comment]
#497
