### ISSUE TITLE
database not registered: /{DATABASE}/{SCHEMA}/{TABLE}

### ISSUE THREAD

**Issue by avelino** [prest/prest#601]
**Describe the bug**
Is not locating the database when accessing the table read endepoint

endpoint: GET `/prest/public/XXX`

```
database not registered: XXX
```

**To Reproduce**
using the existing docker-compose (`docker-compose.yml`) and creating a:
1.`docker-compose up`
2. create this tables in Postgres
```sql
DROP TABLE IF EXISTS "public"."untitled_table_196";
CREATE SEQUENCE IF NOT EXISTS untitled_table_196_id_seq;
CREATE TABLE "public"."untitled_table_196" (
    "id" int4 NOT NULL DEFAULT nextval('untitled_table_196_id_seq'::regclass),
    "name" bpchar(250),
    "age" int8,
    PRIMARY KEY ("id")
);
INSERT INTO "public"."untitled_table_196" ("id", "name", "age") VALUES
(1, '42328934792384krsdjdlfksjd', 10);
```
2. access this endpoint **GET** `/prest/public/untitled_table_196`

**Expected behavior**

**Desktop (please complete the following information):**
 - pREST version (or commit ref): **branch main**
 - pREST endpoint: `/prest/public/untitled_table_196`
 - PostgreSQL version: docker image `postgres:latest`
 - OS: [e.g. Debian Tid]: macOS
 - Go version: 1.17
 - Log gist:

**Additional context**
this bug was implemented in the **singledb** input

on line 112 the database is not set and we are wondering if it is equal to the variable we receive on the endpoint (request), the database is set on line 118, at this point of the `if` it will never exist.

https://github.com/prest/prest/blob/d503bddc3847262670490dabc3909ea5380c6f9a/controllers/tables.go#L112-L118

related:
- [x] #590

**Comment by arxdsilva** [comment]
shouldnt the binary also load the postgres adapter? This should fix it easily
