### ISSUE TITLE
health check endpoint

### ISSUE THREAD

**Issue by avelino** [prest/prest#606]
**Is your feature request related to a problem? Please describe.**
A health check is a special REST API implementation that you can use to validate the status of pREST and its dependencies.

**Describe the solution you'd like**
endpoint: `/_health`

The API endpoint handler performs various checks, such as:
- the status of the connections to the infrastructure services used by the service instance
- the status of the host, e.g. disk space
- application specific logic

**Problem:**
How to detect that a running service instance is unable to handle requests?

**Comment by arxdsilva** [comment]
we can solve the raised problem with a `/liveness` endpoint, this will be only related to the api itself being up and able to respond, while the `/_health` can check for dbs connections. What do you mean by diskspace?

**Comment by george-silva** [comment]
Again! Great product!

Chiming in: I've deployed pREST in ECS, using AWS Copilot. Smooth deploy, but it requires a health check endpoint in order for AWS to consider the "pod" live.

I've been using a common endpoint (databases) for AWS to detect if the app is up, but a `health` endpoint would be glorious.
