### ISSUE TITLE
Error pq: function row_to_json(text) does not exist

### ISSUE THREAD

**Issue by murilofurquim** [prest/prest#623]
I'm trying to use prest and have encountered the following error when trying to insert data:
`{
  "error": "pq: function row_to_json(text) does not exist"
}`
The **GET** request works fine, returning data correctly.

I'm using docker for both postgres and prest, both their latest tags.

Here is the prest docker log:
`2021/11/05 20:14:02 [msg] tables.go:225 pq: function row_to_json(text) does not exist`
`[negroni] 2021-11-05T20:14:02Z | 400 |   794.8µs | localhost:3000 | POST /postgres/public/operacao`

**Comment by avelino** [comment]
@murilofurquim can you describe your environment?

- postgresql version
- prest version

with this we can simulate your environment here

**Comment by arxdsilva** [comment]
`row_to_json` usage: https://github.com/prest/prest/blob/9a14c8131fe369f27029b144e601839a0f67f23d/adapters/postgres/postgres.go#L814

**Comment by avelino** [comment]
@murilofurquim what version of postgres are you using?

the `row_to_json ` function that prestd uses is from postgres itself

**Comment by murilofurquim** [comment]
I have used the python library as a small web server on a script. But I
can't find the source code on my PC. And can't find the example on the
prest site. Can you point me to it? I can only find the documentation on
the docker image.

Em qua., 26 de jan. de 2022 18:46, Avelino ***@***.***>
escreveu:

**Comment by arxdsilva** [comment]
Closing as it is stale and probably related to the postgres version used. 

Msg again with more info so we can debug better and reopen.
