### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [prest/prest#632]
👋  it looks like `1.0.11` was not marked as the latest release, just to raise an issue in here to confirm whether it was intended. Thanks!

cc @avelino 

relates to Homebrew/homebrew-core#90440

**Comment by avelino** [comment]
@chenrui333 we had a problem with the generation of version 1.0.11, I fixed it and we generated version 1.0.12

do i need to do anything in homebrew?

**Comment by chenrui333** [comment]
Yeah, I can help with the homebrew sire, thanks for the fix!

**Comment by chenrui333** [comment]
@avelino looks like we run into the issue again about the latest release, 1.1.3 and 1.1.4 releases were not done cleanly.

relates to https://github.com/Homebrew/homebrew-core/pull/115201

**Comment by avelino** [comment]
cc @arxdsilva
