### ISSUE TITLE
allow count() as group function

### ISSUE THREAD

**Issue by trensetim** [prest/prest#647]
Currently there are several aggregate (here called "group") functions implemented:
https://docs.prestd.com/query-statements/#groupselect-functions-support
https://www.postgresql.org/docs/13/functions-aggregate.html

However that is not the complete list of aggregate functions natively supported by postgres.

I would like to add count(columnName|*) here.

maybe one can explore whether some of the other functions are also worth implementing. But I would like to keep the focus on this issue on count(), because I actively need that currently, to do something like:

select column, count(column)
from table
group by column
;

to have a list of all unique values of "column" with their associated frequency.

**Comment by trensetim** [comment]
Prest == Lovely work btw. ❤️

**Comment by avelino** [comment]
@trensetim to `count` there is the query string parameter with the name `?_count={field name}`
[read more here](https://docs.prestd.com/query-statements/#filters-parameters-query-string---get)

**Comment by trensetim** [comment]
Thanks. I have just tried this on my test database.

Using http://localhost:3010/test/public/person
Results in
[{"id":1,"name":"a","birthday":"1998-05-21","favorite_number":3}, 
 {"id":2,"name":"b","birthday":"1999-11-09","favorite_number":3.1415}, 
 {"id":3,"name":"c","birthday":null,"favorite_number":1}, 
 {"id":4,"name":"c","birthday":null,"favorite_number":2}]

Using http://localhost:3010/test/public/person?_groupby=name
Results in {"error": "pq: column \"person.id\" must appear in the GROUP BY clause or be used in an aggregate function"}

Using http://localhost:3010/test/public/person?_groupby=name&_count=id
Results in {"count":1}

Using http://localhost:3010/test/public/person?_groupby=name&_count=name
Results in {"count":1}

All of those are not what I want.
I would like to receive
[{name:'a', count:1},{name:'b', count:1},{name:'c', count:2}]

How can I achieve this?

Btw. I am running prest/prest:v1.0.12 which seems to be the latest version-pinned image currently.

**Comment by avelino** [comment]
I'm marking this issue as a bug, but I need to do some testing and understand how we are going to resolve this issue

@trensetim do you have a proposal to do this fix?

**Comment by avelino** [comment]
> Using http://localhost:3010/test/public/person?_groupby=name&_count=name
> Results in {"count":1}

accessing the endpoint with the mentioned parameters we execute this sql query:
```sql
SELECT COUNT("name") FROM "prest"."public"."prest_users" GROUP BY "name"
```

## follows my example
**dataset:**
```json
[
  {
    "id": 1,
    "name": "pREST Full Name",
    "username": "prest",
    "password": "8c60e97b9cf709c643e4a583b1ae9cb1",
    "metadata": null
  },
  {
    "id": 2,
    "name": "test",
    "username": "lero2",
    "password": "8c60e97b9cf709c643e4a583b1ae9cb1",
    "metadata": null
  },
  {
    "id": 3,
    "name": "test",
    "username": "lero3",
    "password": "8c60e97b9cf709c643e4a583b1ae9cb1",
    "metadata": null
  }
]
```

**request URI:**
```http
GET /prest/public/prest_users\?_count\=name\&_groupby\=name
```
**response:**
```json
{
  "count": 2
}
```
**query sql _(executed internment by prestd)_:**
```sql
SELECT COUNT("name") FROM "prest"."public"."prest_users" GROUP BY "name"
```

**the correct is to return:**
```json
{
  "count": 2,
  "count": 1,
}
```

had a condition to return the first record as an object (not the object list)
https://github.com/prest/prest/blob/39cd7ca287f6abb6619e8ca2e84276fb59736668/controllers/tables.go#L211-L214

## solution
I think it is worth having the option to return the first record, in some cases I "only" want to know the sum of the record and return it in a list I would have to interact in a list of 1 to get the result, but I agree that should not be the default behavior.

Thinking about this we are implementing a parameter called `_count_first` that will have the behavior to bring the first record, when not passed it will bring the list of records as it works in the execution of the query in postgres

**Comment by trensetim** [comment]
This is awesome. To answer my own question according to your new version: I have to call
```
GET /prest/public/prest_users\?_count\=name\&_groupby\=name&_select\=name
```
Which gives me exactly what I expected:
```
[{"count":1,"name":"a"}, 
 {"count":1,"name":"b"}, 
 {"count":2,"name":"c"}]
```

**Comment by avelino** [comment]
@trensetim yep, did it behave differently?

**Comment by trensetim** [comment]
Well it behaves as I expect it now. So huge thanks and this issue is solved for me 👍
