### ISSUE TITLE
Documentation duplicate "page_size" vs "_page_size"

### ISSUE THREAD

**Issue by trensetim** [prest/prest#648]
**Describe the bug**
The documentation https://docs.prestd.com/query-statements/#filters-parameters-query-string---get states that there are the parameters "page_size" and "_page_size"; and "page" and "_page".
However this seems to be a duplicate because "page" and "page_size" do not work on prest/prest:v1.0.12

**To Reproduce**
Query http://localhost:3011/database/schema/table?_page_size=2&_page=1 --> Acceptable Result
Query http://localhost:3011/database/schema/table?page_size=2&page=1 --> {"error": "pq: column \"page_size\" does not exist"}

**Expected behavior**
Documentation should not state "page" and "page_size"
![grafik](https://user-images.githubusercontent.com/74014803/147200115-5786102c-fa38-4397-b43b-fb42c7d6f5e5.png)

**Comment by avelino** [comment]
thank you for reporting this error

contextualizing: the documentation was born before the code and when we started developing prestd (in 2016) we set the default to use prefix underline `_` in the query string parameters
