### ISSUE TITLE
How can I filter using timestamp or a range of timestamps?

### ISSUE THREAD

**Issue by dariocf1** [prest/prest#671]
I need to get a group of rows from a specific date range (stored as timestamp), I don't want to use custom query, I want to achive this using parameters. 

The documentation doesn't show any example, please, Any already did it?

**Comment by avelino** [comment]
@dariocf1 to filter by time range should be like this:

I apologize for not having this documented in our documentation before you opened the issue.

Here's a unit test where we do it with time range: 
https://github.com/prest/prest/blob/6375325d0e5a4b531090392014ebe6dc63f0a7d3/adapters/postgres/postgres_test.go#L176

**Comment by dariocf1** [comment]
Great, Thank you @avelino!
