### ISSUE TITLE
Plugin custom status code

### ISSUE THREAD

**Issue by dariocf1** [prest/prest#687]
Hi, 

I'm using plugin functionality and I want to return a different status code (such as 401 or 404) with specific message. The only response allowed is a string. I tried to create and throw an error, but it does not worked I got an 500 status code.

Is there any way to change the status code from the response in the plugin?

Thanks in advance!

**Comment by avelino** [comment]
Great point @dariocf1 , no thought was given to other types of status codes

Let's plan the implementation, can you propose an implementation?

**Comment by sod-lol** [comment]
I want to work on this. can i try?

**Comment by vmesel** [comment]
@sod-lol of course!

**Comment by arxdsilva** [comment]
@dariocf1 we've added the possibility to return an error, will close this but feel free to reopen if necessary.
