### ISSUE TITLE
Contribution guide link needs to be updated

### ISSUE THREAD

**Issue by anupam-absa** [prest/prest#690]
**Contribution guide link needs to be updated**
The link to the contribution guide returns 404 error. The current route is **/contribute** which seems to be old. The new contribute guide link is **/contribution**

**To Reproduce**
1. Go to the repository home page - https://github.com/prest/prest 
2. Scroll down to the section where it says "Want to contribute to the project and don't know ...."
3. Click on the link "here"

**Expected behavior**
User should be landed in the contribute guide page

**Actual behavior**
User sees 404 error

**Possible solution**
Link needs to be updated from /contribute to /contribution

**Screenshots for reference**
![SCR-20220401-vsw](https://user-images.githubusercontent.com/11215955/161312418-5bdc69eb-9972-4ee4-acf5-349818dd7ba9.png)
![SCR-20220401-vtn](https://user-images.githubusercontent.com/11215955/161312455-1b8e6b68-c1da-4508-8db4-8765c1947f29.png)
![image](https://user-images.githubusercontent.com/11215955/161312574-42eac5e7-a4ca-47c2-aba9-1719112dac4b.png)

**Comment by avelino** [comment]
@anupam-absa thank you very much for reporting the error in the contribution guide link

**Comment by anupam-absa** [comment]
You're welcome @avelino !
