### ISSUE TITLE
Can not update array field(jsonb based).

### ISSUE THREAD

**Issue by leopku** [prest/prest#692]
**Describe the bug**
Cannot update an array field(jsonb based).

**To Reproduce**
1. PUT Request to endpoint '/{database}/{schema}/{table}/'
```
xh PATCH --raw '{"filedA": ["a","b"]}' :6000/demo/public/movies id==27PNJ0q50AkPvNTaT8YXmhVvrNp
```

3. Response Error
```
{
    "error": "pq: invalid input syntax for type json"
}
```

**Expected behavior**
`fieldA` should be updated with value ["a", "b"]
The `fieldA` can be updated by program wrote by golang

**Desktop (please complete the following information):**
 - pREST version (or commit ref): 1.0.14
 - pREST endpoint: localhost:6000
 - PostgreSQL version:  12+214ubuntu0.1
 - OS: [e.g. Debian Tid]:  Ubuntu 20.04.3 LTS
 - Go version: 1.17.5
 - Log gist:

**Comment by vmesel** [comment]
I'm going to replicate this issue, coming back with answers later today!
