### ISSUE TITLE
add schema variable for prest_users table

### ISSUE THREAD

**Issue by benoitdm-oslandia** [prest/prest#697]
It would be nice to have a parameter to specify a schema name to use when creating or accessing to the `prest_users` table. 

By default, the schema is `public` and in some case it is not specified (so `public` is used as default).

Thanks!

**Comment by avelino** [comment]
your suggestion is extremely important
can you implement your suggestion?

https://github.com/prest/prest/blob/e46c8128446a4024636d056fb235a05edf2e11a9/cmd/auth.go#L12-L33
