### ISSUE TITLE
arm64 docker image needed

### ISSUE THREAD

**Issue by zenz** [prest/prest#702]
Hi,

I'm trying to install pREST for test with my RaspberryPI 4 with docker.

But I found that it doesn't have arm64 support at this moment in docker image.

Can you teams consider to provide it?

Best regards

**Comment by arxdsilva** [comment]
Hi @zenz, I dont think we have any limitation not to provide arm64 support, but for now the best we can do is a beta so everyone can test and later if it is stable provide it properly, what do you think?

**Comment by zenz** [comment]
@arxdsilva Yes, you are right. So where can I select the beta image? is it ready yet?

**Comment by arxdsilva** [comment]
@zenz I've created an image so you can test with the latest version: docker pull `arxdsilva/prest-linux-arm64:v1.1.0`
