### ISSUE TITLE
invalid identifier

### ISSUE THREAD

**Issue by arxdsilva** [prest/prest#725]
However, there is a limitation in the aggregation query through prestd, that is, it must be included in the query parameters _groupby, otherwise it will report an error saying that the column cannot be found. For example, if you want to query the oldest age of five people, you will get the following error. ,

```
~ » curl http://localhost:3000/prestd/prest/persons\?_select\=max:age
{
	"error": "invalid identifier max:age"
}
```
Hopefully prestd will add support for this kind of query statement soon.

https://old-panda.com/2022/03/27/prestd-tutorial-iii/

**Comment by vmesel** [comment]
@arxdsilva so we should add a way for validating the select statement to see if we are using an aggregate function without a group by?

**Comment by vmesel** [comment]
@avelino I got it, assign it to me, pls!
