### ISSUE TITLE
Different JOIN behaviour after prest upgrade

### ISSUE THREAD

**Issue by kalmarz** [prest/prest#746]
**Describe the bug**
Performing the same query when joining tables on different versions of prestd (with the same database backend) produces different outputs.

- prestd 1.0.5 -> OK
- prestd 1.0.14 -> NOK

**To Reproduce**
1. Request to endpoint `scans?_join=inner:bodyfat:scans.scancode:$eq:bodyfat.scancode&scans.scancode=$in.000005256e0dc77adbe8f6b25b75eda6748f0818&bodyfat.method=tina`
2. Attached the CSV file of both output as well as the XLS file for comparison. In the XLS I marked the differences with red. As you see we have different results for the same column `scans.gender` and also for the number of returned columns.

**Expected behavior**
Same and correct query results in both cases.

**Desktop (please complete the following information):**
 - pREST version (or commit ref): as written above
 - pREST endpoint: as written above
 - PostgreSQL version: 14.x
 - OS: [e.g. Debian Tid]: Both API running in Kubernetes Popds
 - Go version: NA
 - Log gist: NA

**Additional context**
Database table structure:

```
                                     Table "public.scans"
    Column     |          Type          | Collation | Nullable |           Default            
---------------+------------------------+-----------+----------+------------------------------
 scancode      | character varying(255) |           | not null | 
 creation_date | bigint                 |           | not null | 
 synthetic     | boolean                |           | not null | 
 creator       | character varying(50)  |           | not null | 
 gender        | character varying(50)  |           | not null | 'neutral'::character varying
 clothes       | boolean                |           |          | 
 fists         | boolean                |           |          | 
 pose          | character varying(50)  |           |          | 
 motion        | character varying(50)  |           |          | 
 scene         | character varying(50)  |           |          | 
 raw_data      | character varying(50)  |           |          | 
 user_id       | character varying(100) |           |          | 
 device_id     | character varying(100) |           |          | 
 age           | bigint                 |           |          | 
 weight        | double precision       |           |          | 
 height        | double precision       |           |          | 
 region        | character varying(50)  |           |          | 
 country       | character varying(50)  |           |          | 
 mocap         | boolean                |           | not null | false
 avatar        | character varying(50)  |           |          | 
 campaign      | character varying(255) |           |          | 
 ref_scan      | character varying(255) |           |          | 
 artefacts     | boolean                |           |          | 
 bad_hair      | boolean                |           |          | 
 bad_feet      | boolean                |           |          | 
 verified      | boolean                |           | not null | false
 ref_motion    | character varying(255) |           |          | 
Indexes:
    "scans_pkey" PRIMARY KEY, btree (scancode) 
```

```
                                     Table "public.bodyfat"
     Column      |          Type          | Collation | Nullable |           Default            
-----------------+------------------------+-----------+----------+------------------------------
 bodyfat_id      | integer                |           | not null | generated always as identity
 scancode        | character varying(255) |           | not null | 
 creation_date   | bigint                 |           | not null | 
 percentage      | numeric(7,2)           |           | not null | 
 method          | character varying(50)  |           | not null | 
 device          | character varying(50)  |           |          | 
 meta_cv_release | character varying(50)  |           |          | 
 fitting_id      | integer                |           |          | 
 gender          | character varying(50)  |           |          | 
Indexes:
    "bodyfat_pkey" PRIMARY KEY, btree (bodyfat_id)
    "bf_creation_date_idx" btree (creation_date)
    "bf_meta_cv_release_idx" btree (meta_cv_release)
    "bf_method_idx" btree (method)
    "bf_scancode_idx" btree (scancode)
Foreign-key constraints:
    "fk_fitting_id" FOREIGN KEY (fitting_id) REFERENCES model_fitting_results(fitting_id) ON DELETE CASCADE
    "fk_scancode" FOREIGN KEY (scancode) REFERENCES scans(scancode) ON DELETE CASCADE
```

Cc: @manhofer
[query_result_comparison.xlsx](https://github.com/prest/prest/files/10154654/query_result_comparison.xlsx)
[WORKING_db_query_result.csv](https://github.com/prest/prest/files/10154655/WORKING_db_query_result.csv)
[NOT_WORKING_db_query_result.csv](https://github.com/prest/prest/files/10154656/NOT_WORKING_db_query_result.csv)

**Comment by vmesel** [comment]
Hey @kalmarz, thanks for the report! We are going to take a look!

**Comment by kalmarz** [comment]
@arxdsilva  thanks for the suggestion. It doesn't really work for us because the API is running in Kubernetes pods and we don't have a persistent volume configured for custom queries. It could be done but it'd be a very complicated workflow.

**Comment by vmesel** [comment]
@kalmarz I'm analyzing your data on Excel. Can you tell me what are the differences on data? I'm colorblind but I do know that there are different colors (probably red or green).

And can you also provide some data samples so I can test with similar data?

**Comment by kalmarz** [comment]
@vmesel In the xls, attached previously, columns H, AH and AI are returned empty with prestd 1.0.14 (row 3). And the expected right answer is in row 7, with prestd 1.0.5. Also attached 2 CSVs, containing 1-1 record for the tables
[bodyfat__db_query_result.csv](https://github.com/prest/prest/files/10260314/bodyfat__db_query_result.csv)
[scans__db_query_result.csv](https://github.com/prest/prest/files/10260315/scans__db_query_result.csv)

**Comment by kalmarz** [comment]
@vmesel I'm not sure I understand this request.
If you need the insert statements then I don't.
If you asking for a query that produces the result I opened the issue for then this is it: `scans?_join=inner:bodyfat:scans.scancode:$eq:bodyfat.scancode&scans.scancode=$in.000005256e0dc77adbe8f6b25b75eda6748f0818&bodyfat.method=tina`

**Comment by vmesel** [comment]
No worries, I got it using Datagrip:

```
insert into public.bodyfat (device, gender, method, scancode, bodyfat_id, fitting_id, percentage, creation_date, meta_cv_release)
values  (null, null, 'tina', '000005256e0dc77adbe8f6b25b75eda6748f0818', 971948, null, 23.22, null, '1.4.0-8899');
```

and 

```
insert into public.scans (scancode, creation_date, synthetic, creator, gender, clothes, fists, pose, motion, scene, raw_data, user_id, device_id, age, weight, height, region, country, mocap, avatar, campaign, ref_scan, artefacts, bad_hair, bad_feet, verified, ref_motion)
values  ('000005256e0dc77adbe8f6b25b75eda6748f0818', null, false, 'manuel', 'male', false, true, 'a', 'turntable', null, null, '5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4', '9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71', 35, 86.37, 175, null, null, false, 'gen1', 'gen1_scans', null, false, false, false, true, null);
```

**Comment by vmesel** [comment]
On commit [e4c6df5 - (Version 1.1.5)](https://github.com/prest/prest/commit/e4c6df5372984c27debbea705022d6aa92cd12dc), on: http://localhost:8080/{database}/public/scans?_join=inner:bodyfat:scans.scancode:$eq:bodyfat.scancode&scans.scancode=$in.000005256e0dc77adbe8f6b25b75eda6748f0818&bodyfat.method=tina, we are getting:

```json
[
  {
    "age": 35,
    "pose": "a",
    "fists": true,
    "mocap": false,
    "scene": null,
    "avatar": "gen1",
    "device": null,
    "gender": null,
    "height": 175,
    "method": "tina",
    "motion": "turntable",
    "region": null,
    "weight": 86.37,
    "clothes": false,
    "country": null,
    "creator": "manuel",
    "user_id": "5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4",
    "bad_feet": false,
    "bad_hair": false,
    "campaign": "gen1_scans",
    "raw_data": null,
    "ref_scan": null,
    "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
    "verified": true,
    "artefacts": false,
    "device_id": "9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71",
    "synthetic": false,
    "bodyfat_id": 971948,
    "fitting_id": null,
    "percentage": 23.22,
    "ref_motion": null,
    "creation_date": null,
    "meta_cv_release": "1.4.0-8899"
  }
]
```
On [version 1.0.14 - commit d9fed6](https://github.com/prest/prest/commit/d9fed6683eeae9d90e42c1ad1c08e1cd90310321), we are getting:

```json
[
  {
    "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
    "creation_date": null,
    "synthetic": false,
    "creator": "manuel",
    "gender": null,
    "clothes": false,
    "fists": true,
    "pose": "a",
    "motion": "turntable",
    "scene": null,
    "raw_data": null,
    "user_id": "5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4",
    "device_id": "9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71",
    "age": 35,
    "weight": 86.37,
    "height": 175,
    "region": null,
    "country": null,
    "mocap": false,
    "avatar": "gen1",
    "campaign": "gen1_scans",
    "ref_scan": null,
    "artefacts": false,
    "bad_hair": false,
    "bad_feet": false,
    "verified": true,
    "ref_motion": null,
    "bodyfat_id": 971948,
    "percentage": 23.22,
    "method": "tina",
    "device": null,
    "meta_cv_release": "1.4.0-8899",
    "fitting_id": null
  }
]
```

And on [version 1.0.5 - commit 384296](https://github.com/prest/prest/commit/38429627d9557385dab8aa8c2de8e71e2f880e2c) we are getting:

```json
[
  {
    "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
    "creation_date": null,
    "synthetic": false,
    "creator": "manuel",
    "gender": null,
    "clothes": false,
    "fists": true,
    "pose": "a",
    "motion": "turntable",
    "scene": null,
    "raw_data": null,
    "user_id": "5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4",
    "device_id": "9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71",
    "age": 35,
    "weight": 86.37,
    "height": 175,
    "region": null,
    "country": null,
    "mocap": false,
    "avatar": "gen1",
    "campaign": "gen1_scans",
    "ref_scan": null,
    "artefacts": false,
    "bad_hair": false,
    "bad_feet": false,
    "verified": true,
    "ref_motion": null,
    "bodyfat_id": 971948,
    "percentage": 23.22,
    "method": "tina",
    "device": null,
    "meta_cv_release": "1.4.0-8899",
    "fitting_id": null
  }
]
```

Using [JSON Diff tool](https://jsondiff.com/), I'm not able to find a difference between JSONs generated from releases 1.0.5 and 1.0.14.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/4984147/208669784-336ed944-8274-4776-b2c8-334ace67bd09.png">

Neither comparing 1.0.14 with our most recent version - 1.1.15:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/4984147/208670102-5ec572bf-45f3-44d0-a4b9-028154fb54b6.png">

 Nor comparing 1.0.5 and 1.1.15:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/4984147/208670328-eff959d1-a6f0-457a-9e4d-b1852c9ba8fa.png">

I will try to read the Excel file again with different fonts so I can try to understand where the difference is. But it seems that the API is stable.

**Comment by vmesel** [comment]
The only difference between the JSONs and CSVs you sent us is that on we didn't insert the creation date as we can see below.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/4984147/208673436-dccd18cd-895c-400b-a658-b66b45fa9eef.png">

**Comment by manhofer** [comment]
The issue is that "gender" exists as a column in both tables, and in the "scans" table it is not null for this row, but in the "bodyfat" table it is null for this row. But in the data we get back from the API "scans.gender" is null (even though it shouldn't be), and "bodyfat.gender" is missing altogether. In previous versions of the API we always got back both columns with their respective values.

**Comment by kalmarz** [comment]
@vmesel Thank you for the through investigation!

This is weird. :) I just ran the query against both versions with Postman. The 2 JSONs are clearly not identical, see below the multiple gender columns in the second JSON. Yet the JSON Diff tool indeed shows them as "semantically identical".
¯\_(ツ)_/¯

```
/app$ prestd version  
Simplify and accelerate development, ⚡ instant, realtime, high-performance on any Postgres application, existing or new 1.0.14

[
    {
        "age": 35,
        "pose": "a",
        "fists": true,
        "mocap": false,
        "scene": "",
        "avatar": "gen1",
        "device": null,
        "gender": null,
        "height": 175,
        "method": "tina",
        "motion": "turntable",
        "region": "",
        "weight": 86.37,
        "clothes": false,
        "country": "",
        "creator": "manuel",
        "user_id": "5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4",
        "bad_feet": false,
        "bad_hair": false,
        "campaign": "gen1_scans",
        "raw_data": "",
        "ref_scan": "",
        "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
        "verified": true,
        "artefacts": false,
        "device_id": "9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71",
        "synthetic": false,
        "bodyfat_id": 971948,
        "fitting_id": null,
        "percentage": 23.22,
        "ref_motion": "",
        "creation_date": 1637367261,
        "meta_cv_release": "1.4.0-8899"
    }
]
```

```
/app $ ./prestd version
Serve a RESTful API from any PostgreSQL database 1.0.5

[
    {
        "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
        "creation_date": 1573918817,
        "synthetic": false,
        "creator": "manuel",
        "gender": "male", <--------------- this column is missing from the first result above
        "clothes": false,
        "fists": true,
        "pose": "a",
        "motion": "turntable",
        "scene": "",
        "raw_data": "",
        "user_id": "5edbf33e52549fb269123d6eb3e6986bea6c4e03dcbd5223c8591ac25f1a95d4",
        "device_id": "9fed0cec52a189e77e418dd123d61e03eaffbdf3910deccbd746b8c91804ca71",
        "age": 35,
        "weight": 86.37,
        "height": 175,
        "region": "",
        "country": "",
        "mocap": false,
        "avatar": "gen1",
        "campaign": "gen1_scans",
        "ref_scan": "",
        "artefacts": false,
        "bad_hair": false,
        "bad_feet": false,
        "verified": true,
        "ref_motion": "",
        "bodyfat_id": 971948,
        "scancode": "000005256e0dc77adbe8f6b25b75eda6748f0818",
        "creation_date": 1637367261,
        "percentage": 23.22,
        "method": "tina",
        "device": null,
        "meta_cv_release": "1.4.0-8899",
        "fitting_id": null,
        "gender": null
    }
]
```

**Comment by manhofer** [comment]
@vmesel the json results you posted above only show the column name as key, rather than e.g. `<table>.<column>` as it would have to be to support that two linked tables can have columns with the same name. In the past, this seemed to work though

**Comment by vmesel** [comment]
@manhofer can you provide us the generated query that pREST provides when `PREST_DEBUG = true`?

**Comment by kalmarz** [comment]
@vmesel there you go:

`2022/12/23 09:26:04 [debug] server.go:2084 generated SQL:SELECT jsonb_agg(s) FROM (SELECT * FROM "alexandria"."public"."scans" LEFT JOIN "bodyfat" ON "scans"."scancode" = "bodyfat"."scancode"  WHERE "scans"."scancode" IN ($1) AND "bodyfat"."method" = $2 ) s parameters: [000005256e0dc77adbe8f6b25b75eda6748f0818 tina]`

**Comment by kalmarz** [comment]
@vmesel I'm wondering if you had a chance to look into the issue?

**Comment by kalmarz** [comment]
@vmesel @arxdsilva this is still important for us so I did some debugging.

At some point in the development you switched from `json_agg()` to `jsonb_agg()` Postgres function in the `SELECT` queries. And this is exactly what kills our join attempts. I'm not an expert but `jsonb_agg()` seems to be aggregating the similarly named columns from both tables into a single column.

In our case, for example, whe have a `gender` column in both tables but only one is present in the response. I admit that the DB has some room for improvement when it comes down to normalization but for now it is what it is.

While I patched our API to use `json_agg()` and it seems to be working fine I'm not sure if this would be the right approach on the long term. So if you have ideas I'm more than open hearing them.

I'm thinking whether putting the aggregation function into a configurable environment variable would be a potential solution?

**Comment by arxdsilva** [comment]
@kalmarz we've just released `v1.4.0` to address your issue

**Comment by arxdsilva** [comment]
@kalmarz you are welcome, sorry for the long delay, lots of small things had to be fixed before we were able to release this.

**Comment by kalmarz** [comment]
no worries, I patched the code temporarily in the mean time.
