### ISSUE TITLE
Error in Template Functions

### ISSUE THREAD

**Issue by caiolul** [prest/prest#749]
Hi guys, I'm using the `inFormat` template function for an IN clause in a SQL file, as shown in the docs example. I've discovered a detail: it can't do the IN because of a formatting error.

Using it as the query params it turns out that it only joins the options.

`http://localhost:8081/_QUERIES/dir/customquery?field1=test1,test2`

```sql
SELECT * FROM table WHERE name IN {{inFormat "field1"}};
```

And what I got was basically the combination of these terms.

```sql
name in ('test1,test2')
```

The solution I found was to add quotes to complete the name (i.e.: `?field1=test1','test2`), however, this is a terrible solution and looks like SQL Injection (LOL). Going deeper into the code and doing some tests on this function, I noticed that it tries to transform the string into a string slice.

https://github.com/prest/prest/blob/b7107b18d277e85f3155d5eb015dfd9c8a8a729c/template/funcregistry.go#L42-L50

Following this concept, what I've done was: The function receives the string and after that, it's sliced into `[]string`.

```golang
str := fr.TemplateData[key].(string)
split := strings.Split(str, ",")
query = fmt.Sprintf("('%s')", strings.Join(split, "', '"))
```

I saw that there is a split function but I couldn't use it inside `inFormat`.

 - pREST: latest version
 - pREST endpoint: custom query
 - PostgreSQL version: 12
 - OS: Manjaro Linux x86_64
 - Go version: go1.19.4 Linux/amd64
 - Log gist: https://gist.github.com/caiolul/14e908f4f845b3b2cf31c84ec9268b11

**Comment by vmesel** [comment]
@avelino @arxdsilva can you guys take a look? I'm working with @caiolul at Mais Retorno and we went through this issue together

**Comment by vmesel** [comment]
Something we need to fix after solving this issue (if it's a real issue is documenting this function better on the docs). Our docs don't offer a very descriptive way of using this function.

**Comment by vmesel** [comment]
As I spoke to @arxdsilva, it's not actually a bug. To send multiple parameters to `inFormat` function, you instantiate it with multiple calls of the same field on the URL.

An example:

I need to retrieve multiple hedge funds with IBOV and CDI as indexers, the query would be:

```sql
SELECT * FROM hedge_funds WHERE fund_benchmark in {{inFormat "benchmark_field" }}
```

And the URL to be called would be: `/_QUERIES/your_awesome_query_folder/awesome_query?benchmark_field=IBOV&benchmark_field=CDI`

**Comment by arxdsilva** [comment]
Hi @caiolul , thanks for reporting, this is a valid problem that we dont solve right now. From what I can see in the code, we've opted to support queries only with this format:

```url
https://.../_QUERIES/<folder>/<query>?field=<value1>&field=<value2>
```

As is said in [this article](https://hugomartins.io/essays/2021/02/how-to-pass-multiple-values-to-http-query-parameter/),  the [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) talks that web servers **could** have both the previous cited implementation and `field=val1,val2` working, but neither are mandatory. Although I believe that having both working is great for us, so we definately should have it implemented in the future in prestd.

I'll keep this open so we can track this.

**Comment by vmesel** [comment]
@arxdsilva I'm going to work on this, if you want to pair, let me know!

**Comment by vmesel** [comment]
Solved!
