### ISSUE TITLE
Redshift support is not working

### ISSUE THREAD

**Issue by vmesel** [prest/prest#757]
**Describe the bug**
Whenever using a Redshift cluster, the query will fail. Redshift doesn't have `JSON_AGG`, `JSONB_AGG`, `JSON_BUILD_OBJECT` functions. More resources: [StackOverflow Issue](https://stackoverflow.com/questions/64170540/json-agg-and-json-build-object-in-redshift) and [Redshift Docs](https://docs.aws.amazon.com/redshift/latest/dg/json-functions.html)

```json
{
"error": "pq: column \"s\" does not exist in s"
}
```

**To Reproduce**
1. Setup a Redshift connection
2. Access a custom query or a URL for a specific table on the database.
3. See the error popping on your screen

**Expected behavior**
The expected behavior would be that the page displayed the results of the table.

**Desktop (please complete the following information):**
 - pREST version (or commit ref): 71c7eda
 - pREST endpoint: /{database}/{schema}/{table}
 - Redshift Version: 1.0
 - OS: [e.g. Debian Tid]: MacOS Ventura Version 13.0.1 (22A400)
 - Go version: go version go1.19.2 darwin/amd64
 - Log gist:

**Comment by avelino** [comment]
@vmesel the simplest way would be to support redshift's JSON function, but ~"we have no way"~ to identify if the connection is with redshift or Postgres (other than identifying it via the connection parameter `?OpenSourceSubProtocolOverride=true`, which does not explicitly say that it is redshift).

I would split the implementation into two parts to have visibility into the problems we will experience supporting redshift:
1. changing the JSON function by reading the connection parameter `?OpenSourceSubProtocolOverride=true` and changing the `JSON` function name
2. implement our JSON serializer as we talked about in this issue #730

**Comment by vmesel** [comment]
As I didn't continue to work with RedShift, I'm closing this issue
