### ISSUE TITLE
prest 1.2.1 release build was not done successfully

### ISSUE THREAD

**Issue by chenrui333** [prest/prest#778]
👋 it looks like 1.2.1 release build was not done successfully, see [the workflow run](https://github.com/prest/prest/actions/runs/4123899195/jobs/7122484947). Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/122676

**Comment by vmesel** [comment]
Thanks for letting us know, @chenrui333 !

**Comment by chenrui333** [comment]
np at all!

**Comment by arxdsilva** [comment]
Hi @chenrui333 , I’ve now fixed the publishing of prestd, please skip v1.2.1 as it’s not fixable within our workflow

**Comment by chenrui333** [comment]
yeah, totally, we actually have shipped [prestd 1.2.2](https://github.com/Homebrew/homebrew-core/pull/123010), thanks for the quick turnaround!
