### ISSUE TITLE
JWT Middleware accepts expired tokens

### ISSUE THREAD

**Issue by kalmarz** [prest/prest#783]
Hi,

I can't rule out that I might be missing something in the config but I don't know what it is. Prestd (v1.2.2 in this case but so behaved v1.1.5 similarly) is working perfectly fine with expired JWT tokens too. So having a token is for life. The env vars I altered:

```
PREST_JWT_KEY=...
PREST_AUTH_TYPE=basic
PREST_DEBUG=false
PREST_AUTH_ENABLED=true
DATABASE_URL=postgres://...
```

Let me know if additional info needed. Any guidance would be greatly appreciated.

**Comment by arxdsilva** [comment]
Hi @kalmarz, thanks for reporting, this is a known issue, we want to solve it in the next patch, but we also got some problems that might line before this.
