### ISSUE TITLE
How to inserted into jsonb field?

### ISSUE THREAD

**Issue by toplinuxsir** [prest/prest#815]
I have table
```
t_mydata (
id integer,
data jsonb,
)
```

when post the body json 
```
{
  id: 111,
data: {"a":1, "b":2}
}
```

error
```
{
    "error": "sql: converting argument $5 type: unsupported type map[string]interface {}, a map"
}
```

**Comment by avelino** [comment]
example test `insert` in `jsonb` field:

https://github.com/prest/prest/blob/c3ea6642fa221c15bbae388ef0e79017cc24a879/controllers/tables_test.go#L166-L204

**in cURL:**

```sh
curl -i -X POST '/DATABASE-NAME/public/t_mydata' \
  -H 'Content-Type: application/json'
  -d '{"id": 111, "data": "{"a":1, "b":2}"}'
```

**data field:** as it is in an http request it is necessary to pass it via string

**Comment by toplinuxsir** [comment]
@avelino 
I create test table t_test(id integer, data jsonb)
```
curl -i -X POST 'http://127.0.0.1:8082/mydb/public/t_test' \
                         -H 'Content-Type: application/json' \
                         -d '{"id": 111, "data": "{"a":1, "b":2}"}'
HTTP/1.1 400 Bad Request
Content-Type: application/json
Vary: Origin
X-Content-Type-Options: nosniff
Date: Fri, 05 May 2023 00:03:11 GMT
Content-Length: 99

{
        "error": "could not perform InsertInTables: invalid character 'a' after object key:value pair"
}⏎                               
```

**Comment by toplinuxsir** [comment]
@avelino  How to resolve the problem ? Thanks!
'```
could not perform InsertInTables: invalid character 'a' after object key:value pair"
```

**Comment by vmesel** [comment]
@toplinuxsir the problem pointed through the message regards your string payload. Try using single quotes instead of double quotes. If it doesn't solve the problem, we will try to replicate the error on our side.

**Comment by toplinuxsir** [comment]
> @toplinuxsir the problem pointed through the message regards your string payload. Try using single quotes instead of double quotes. If it doesn't solve the problem, we will try to replicate the error on our side.



with postman I have changed double quotes to single quote,   it dosen't solve the problem
with python scripts it works!
```
import requests
import json

url = "http://10.192.2.19:8082/mydb/public/t_test"

payload = json.dumps({
  "id": 113,
  "data": json.dumps( {
    "M101-C": 1.5,
    "M102-C" :2,
    "BX01-M": 4,
  })
})
headers = {
  'Content-Type': 'application/json',
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

```

**Comment by avelino** [comment]
I invested some time to test your difficulty using pREST (making requests with cURL)

**create table:**
```sql
CREATE TABLE t_mydata (
  id INT,
  data JSONB
);
```

**cURL:**
```sh
curl -i -X POST 'http://127.0.0.1:3000/prest/public/t_mydata' \
  -H 'Content-Type: application/json' \
  -d '{"id": 80, "data": "{\"a\": 123}"}'
```

*output:*

```
HTTP/1.1 201 Created
Content-Type: application/json
Vary: Origin
Date: Sat, 06 May 2023 17:59:36 GMT
Content-Length: 27

{"id":80,"data":{"a": 123}}
```

> our documentation had no example, I just updated it by putting the example above [here](https://docs.prestd.com/prestd/docs/api-reference/advanced-queries/#jsonb-support)

*@toplinuxsir sorry, but we have a lot to improve in our documentation, we accept your support to improve*
