### ISSUE TITLE
semicolon at the end of custom query raise syntax issue and query fails

### ISSUE THREAD

**Issue by moinologics** [prest/prest#859]
as in documentation of custom query https://docs.prestd.com/api-reference/custom-queries there is a semicolon in the end of each sql but if you put it inside custom query file, it will raise error without proper error message and its confusing.

please remove `;` from Custom Queries docs.

just raising this as i have spend too much time to resolve this.

**Comment by arxdsilva** [comment]
Hey, thanks for letting us know, I've done the necessary changes in our docs: https://docs.prestd.com/api-reference/custom-queries
