### ISSUE TITLE
What happend to the website (prestd.com)

### ISSUE THREAD

**Issue by advdv** [prest/prest#904]
If i go to https://prestd.com/ it seems to only serve ads. While the internet archive suggest this was not the case until recently: https://web.archive.org/web/20241001100545/https://prestd.com/? 

Is there an alternative place to browse the documentation?

**Comment by arxdsilva** [comment]
Hi @advdv , seems that it expired and was not renewed by our project founders, but im working on putting an alternate domain online so we can at least have the website/docs back on.

**Comment by arxdsilva** [comment]
solved
